--ricerca di ausilii per un codice iso
SELECT * FROM AUSILIO_EFFETTIVO WHERE CodiceISO = '12.03.03';

SELECT NOME, CATEGORIA, DESCRIZIONE, EVENTUALINOTE 
FROM AUSILIO A, AUSILIO_EFFETTIVO AE 
WHERE A.CODICEISO=AE.CODICEISO AND A.CODICEISO= '12.03.03';

--con vista
CREATE OR REPLACE VIEW SPECIFICHE_AUSILI AS
SELECT NOME, CATEGORIA, DESCRIZIONE, EVENTUALINOTE, A.CODICEISO
FROM AUSILIO A, AUSILIO_EFFETTIVO AE 
WHERE A.CODICEISO=AE.CODICEISO;

select * from SPECIFICHE_AUSILI WHERE CODICEISO = '12.03.03';

--reperire i dati di una visita
SELECT V.IDVISITA, P.NOME AS NOME_PROFESSIONISTA, P.COGNOME AS COGNOME_PROFESSIONISTA, C.NOME AS NOME_CENTRO, U.NOME AS NOME_UTENTE, U.COGNOME AS COGNOME_UTENTE 
FROM PROFESSIONISTA P, CENTRO C, VISITA V, SVOLGIMENTO S, UTENTE_REGISTRATO U
WHERE P.CF=V.CF AND C.IDCENTRO=V.IDCENTRO AND S.IDVISITA=V.IDVISITA AND S.ID=U.ID;

--con vista
CREATE VIEW SPECIFICHE_VISITA AS
SELECT V.IDVISITA, V.DATA, P.CF, P.NOME AS NOME_PROFESSIONISTA, P.COGNOME AS COGNOME_PROFESSIONISTA, C.NOME AS NOME_CENTRO, U.NOME AS NOME_UTENTE, U.COGNOME AS COGNOME_UTENTE 
FROM PROFESSIONISTA P, CENTRO C, VISITA V, SVOLGIMENTO S, UTENTE_REGISTRATO U
WHERE P.CF=V.CF AND C.IDCENTRO=V.IDCENTRO AND S.IDVISITA=V.IDVISITA AND S.ID=U.ID;

SELECT * FROM SPECIFICHE_VISITA WHERE IDVISITA = 10;

--visualizzare l'ausilio più venduto per ogni azienda
--con vista
CREATE VIEW CONTEGGIO_RICHIESTE AS
SELECT AU.CODICEISO, AU.NOME, A.RAGIONESOCIALE, COUNT(R.IDRICHIESTA) AS NUMERO_RICHIESTE
FROM AUSILIO AU, AZIENDA A, RICHIESTO R
WHERE AU.PARTITAIVA=A.PARTITAIVA AND AU.CODICEISO=R.CODICEISO
group by A.RAGIONESOCIALE, AU.NOME, AU.CODICEISO;

SELECT RAGIONESOCIALE, NOME, CODICEISO, NUMERO_RICHIESTE
FROM CONTEGGIO_RICHIESTE C1
WHERE NUMERO_RICHIESTE = (
    SELECT MAX(NUMERO_RICHIESTE) 
    FROM CONTEGGIO_RICHIESTE C2 
    WHERE C2.RAGIONESOCIALE = C1.RAGIONESOCIALE
);

--visualizzare numero di professionisti sanitari in un centro
SELECT C.NOME, COUNT(P.CF) AS NUMERO_PROFESSIONISTI
FROM PROFESSIONISTA P, CENTRO C
WHERE P.IDCENTRO=C.IDCENTRO
GROUP BY C.NOME;

--visualizzare il numero di vendite per ogni ausilio
SELECT NOME, NUMERO_RICHIESTE FROM CONTEGGIO_RICHIESTE;

--visualizzare il numero di visite fatte in una data da un professionista
SELECT CF, DATA, COUNT(IDVISITA) FROM SPECIFICHE_VISITA
WHERE DATA = '2024-05-10' AND CF ='RSSMRA75A01H501U'
GROUP BY CF, DATA;

SELECT CF, DATA, COUNT(IDVISITA) FROM SPECIFICHE_VISITA
WHERE DATA = '2024-05-12' AND CF ='RSSMRA75A01H501U'
GROUP BY CF, DATA;

-- visualizzare il numero di visite effettuate in ogni centro
SELECT NOME_CENTRO, COUNT(IDVISITA) 
FROM SPECIFICHE_VISITA
GROUP BY NOME_CENTRO;

-- visualizzare i professionisti di ogni centro In ordine crescente di stipendio

SELECT IDCENTRO, STIPENDIONETTO, NOME, COGNOME FROM PROFESSIONISTA
GROUP BY IDCENTRO, NOME, COGNOME, STIPENDIONETTO
ORDER BY IDCENTRO, STIPENDIONETTO;

--visualizzare lo stipendio medio dei professionisti di ogni centro
SELECT C.NOME, AVG(STIPENDIONETTO) FROM PROFESSIONISTA P, CENTRO C
WHERE P.IDCENTRO=C.IDCENTRO
GROUP BY C.NOME;

--selezionare le visite fatte dai supervisori di ogni centro
SELECT IDVISITA, NOME_PROFESSIONISTA, COGNOME_PROFESSIONISTA, NOME_CENTRO, NOME_UTENTE, COGNOME_UTENTE 
FROM SPECIFICHE_VISITA SP, SUPERVISIONE S
WHERE SP.CF=S.CF;

--testing funz
SELECT CodiceISO, NumeroAusiliDisponibili
FROM AUSILIO
WHERE CodiceISO = '12.03.03';

-- Utente 1 richiede ausilio '12.03.03'
CALL esegui_richiesta(5, '12.03.03');

SELECT CodiceISO, NumeroAusiliDisponibili
FROM AUSILIO
WHERE CodiceISO = '12.03.03';